runtime: python39
service: slicer

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_concurrent_requests: 50

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)$
    static_files: \1
    upload: (.*)
